In [1]:
import os
os.chdir('..')

In [2]:
%pwd

'd:\\Programing\\AI_Project\\NLP\\Projects\\Book_Recommender_system'

In [3]:
import pandas as pd

In [4]:
book = pd.read_csv(r"Prectices\archive\Books.csv")
rating = pd.read_csv(r"Prectices\archive\Ratings.csv")
user = pd.read_csv(r"Prectices\archive\Users.csv")

C:\Users\deepu\AppData\Local\Temp\ipykernel_15800\4176500650.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  book = pd.read_csv(r"Prectices\archive\Books.csv")

In [5]:
book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [6]:
user.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [7]:
rating.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [8]:
print(book.shape)
print(user.shape)
print(rating.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [9]:
user.isna().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [10]:
rating.isna().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [11]:
book.isna().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

### Popularity based Recommendation System

In [13]:
rating

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [14]:
book

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

#### here we going to Desinge popularity based recommendation system with the help of rating, so i am going to merge book data and rating dataset with the help of `ISBN` columns becuase in both data set i have only `ISBN` common columns so,.. Let's Marge both dataset

In [15]:
new_data = rating.merge(book, on='ISBN')

In [16]:
new_data.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...

In [17]:
new_data = new_data[['Book-Rating', 'Book-Title', 'Book-Author',
       'Year-Of-Publication', 'Publisher', 'Image-URL-S', 'Image-URL-M',
       'Image-URL-L']]

In [25]:
num_rating = new_data.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [26]:
num_rating

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [27]:
num_rating.rename(columns={'Book-Rating':'num_rating'}, inplace= True)

In [28]:
num_rating

                                               Book-Title  num_rating
0        A Light in the Storm: The Civil War Diary of ...           4
1                                   Always Have Popsicles           1
2                    Apple Magic (The Collector's series)           1
3        Ask Lily (Young Women of Faith: Lily Series, ...           1
4        Beyond IBM: Leadership Marketing and Finance ...           1
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.           2
241067                     Ã?Â?rger mit Produkt X. Roman.           4
241068                                Ã?Â?sterlich leben.           1
241069                              Ã?Â?stlich der Berge.           3
241070                                  Ã?Â?thique en toc           2

[241071 rows x 2 columns]

In [29]:
print(new_data['Book-Rating'].unique())

[ 0  5  9  8  6  7  4 10  3  2  1]

In [30]:
new_data.loc[:, 'Book-Rating'] = new_data['Book-Rating'].astype(int)

In [31]:
new_data['Book-Rating'] = pd.to_numeric(new_data['Book-Rating'], errors='coerce')
avg_rating = new_data.groupby('Book-Title')['Book-Rating'].mean().reset_index()

In [32]:
avg_rating.rename(columns={"Book-Rating":"avg-rating"}, inplace= True)

In [33]:
avg_rating

                                               Book-Title  avg-rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [34]:
popularity_df = num_rating.merge(avg_rating, on='Book-Title')
popularity_df

,Book-Title,num_rating,avg-rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [35]:
popularity_df.isna().sum()

Book-Title    0
num_rating    0
avg-rating    0
dtype: int64

In [38]:
populer_book = popularity_df[popularity_df['num_rating']>250].sort_values(by='num_rating',ascending=False).head(50)
populer_book

,Book-Title,num_rating,avg-rating
234951,Wild Animus,2502,1.019584
196326,The Lovely Bones: A Novel,1295,4.468726
183573,The Da Vinci Code,898,4.642539
5303,A Painted House,838,3.231504
199237,The Nanny Diaries: A Novel,828,3.530193
27922,Bridget Jones's Diary,815,3.527607
206502,The Secret Life of Bees,774,4.447028
52983,Divine Secrets of the Ya-Ya Sisterhood: A Novel,740,3.437838
204387,The Red Tent (Bestselling Backlist),723,4.334716
14392,Angels &amp; Demons,670,3.708955
107962,Life of Pi,664,4.088855
162651,Snow Falling on Cedars,662,3.252266
209298,The Summons,655,3.432061
200253,The Notebook,650,3.560000
210064,The Testament,617,3.179903
85957,House of Sand and Fog,588,3.030612
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
201692,The Pelican Brief,581,2.611015
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
189266,The Girls' Guide to Hunting and Fishing,573,3.139616
169201,Summer Sisters,573,3.361257
187702,The Firm,569,3.080844
202244,The Pilot's Wife : A Novel,568,3.593310
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
179274,The Brethren,556,2.850719
193428,The Joy Luck Club,555,3.055856
219349,Timeline,552,3.750000
6980,A Time to Kill,549,3.122040
209117,The Street Lawyer,545,2.851376
74750,Girl with a Pearl Earring,526,4.218631
205523,The Runaway Jury,520,2.880769
219741,To Kill a Mockingbird,510,4.700000
818,1st to Die: A Novel,509,3.575639
180737,The Chamber,509,3.015717
93210,Interview with the Vampire,508,3.551181
191824,The Horse Whisperer,507,2.686391
204000,The Rainmaker,501,2.922156
119580,Message in a Bottle,496,2.778226
202550,The Poisonwood Bible: A Novel,494,3.609312
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
76343,Good in Bed,490,4.055102
97767,Jurassic Park,488,3.428279
181392,The Client,483,3.084886
55358,Dreamcatcher,481,3.212058
201472,The Partner,478,3.290795
159301,She's Come Undone (Oprah's Book Club),468,3.570513
79829,Hannibal,468,2.760684
204153,The Reader,466,3.012876
193881,The King of Torts,458,3.039301
170101,Suzanne's Diary for Nicholas,457,3.820569

In [42]:
top_50_book = populer_book.merge(book, on='Book-Title').drop_duplicates('Book-Title')[['Book-Title', 'num_rating','Book-Author',
       'Year-Of-Publication', 'Publisher',
       'Image-URL-L']]
top_50_book.shape

(50, 6)

### Here is my top 50 Book which i will show on my home page

In [43]:
top_50_book

,Book-Title,num_rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,Wild Animus,2502,Rich Shapero,2004,Too Far,http://images.amazon.com/images/P/0971880107.0...
1,The Lovely Bones: A Novel,1295,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...
2,The Da Vinci Code,898,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...
8,A Painted House,838,John Grisham,2001,Dell Publishing Company,http://images.amazon.com/images/P/044023722X.0...
13,The Nanny Diaries: A Novel,828,Emma McLaughlin,2002,St. Martin's Press,http://images.amazon.com/images/P/0312278586.0...
15,Bridget Jones's Diary,815,Helen Fielding,1997,Picador (UK),http://images.amazon.com/images/P/0330332775.0...
21,The Secret Life of Bees,774,Sue Monk Kidd,2003,Penguin Books,http://images.amazon.com/images/P/0142001740.0...
27,Divine Secrets of the Ya-Ya Sisterhood: A Novel,740,Rebecca Wells,1997,Perennial,http://images.amazon.com/images/P/0060928336.0...
30,The Red Tent (Bestselling Backlist),723,Anita Diamant,1998,Picador USA,http://images.amazon.com/images/P/0312195516.0...
31,Angels &amp; Demons,670,Dan Brown,2001,Pocket Star,http://images.amazon.com/images/P/0671027360.0...
36,Life of Pi,664,Yann Martel,2002,Harcourt,http://images.amazon.com/images/P/0151008116.0...
40,Snow Falling on Cedars,662,David Guterson,1994,Harcourt,http://images.amazon.com/images/P/0151001006.0...
47,The Summons,655,John Grisham,2002,Dell Publishing Company,http://images.amazon.com/images/P/0440241073.0...
51,The Notebook,650,Nicholas Sparks,1998,Warner Books,http://images.amazon.com/images/P/0446605239.0...
56,The Testament,617,John Grisham,1999,Dell,http://images.amazon.com/images/P/0440234743.0...
63,House of Sand and Fog,588,Andre Dubus III,2000,Vintage Books,http://images.amazon.com/images/P/0375727345.0...
65,Where the Heart Is (Oprah's Book Club (Paperba...,585,Billie Letts,1998,Warner Books,http://images.amazon.com/images/P/0446672211.0...
66,The Pelican Brief,581,John Grisham,1993,Dell,http://images.amazon.com/images/P/0440214041.0...
69,Harry Potter and the Sorcerer's Stone (Harry P...,575,J. K. Rowling,1999,Arthur A. Levine Books,http://images.amazon.com/images/P/059035342X.0...
71,The Girls' Guide to Hunting and Fishing,573,Melissa Bank,2000,Penguin Books,http://images.amazon.com/images/P/0140293248.0...
75,Summer Sisters,573,Judy Blume,1998,Delacorte Press,http://images.amazon.com/images/P/0385324057.0...
79,The Firm,569,John Grisham,1991,Doubleday Books,http://images.amazon.com/images/P/0385416342.0...
86,The Pilot's Wife : A Novel,568,Anita Shreve,1999,Back Bay Books,http://images.amazon.com/images/P/0316601950.0...
87,Harry Potter and the Chamber of Secrets (Book 2),556,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...
90,The Brethren,556,JOHN GRISHAM,2000,Doubleday,http://images.amazon.com/images/P/0385497466.0...
95,The Joy Luck Club,555,Amy Tan,1994,Prentice Hall (K-12),http://images.amazon.com/images/P/0804106304.0...
98,Timeline,552,MICHAEL CRICHTON,2000,Ballantine Books,http://images.amazon.com/images/P/0345417623.0...
105,A Time to Kill,549,JOHN GRISHAM,1992,Dell,http://images.amazon.com/images/P/0440211727.0...
112,The Street Lawyer,545,JOHN GRISHAM,1999,Dell,http://images.amazon.com/images/P/0440225701.0...
117,Girl with a Pearl Earring,526,Tracy Chevalier,2001,Plume Books,http://images.amazon.com/images/P/0452282152.0...
118,The Runaway Jury,520,JOHN GRISHAM,1997,Dell,http://images.amazon.com/images/P/0440221471.0...
124,To Kill a Mockingbird,510,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...
132,1st to Die: A Novel,509,James Patterson,2002,Warner Vision,http://images.amazon.com/images/P/0446610038.0...
134,The Chamber,509,John Grisham,1994,Doubleday Books,http://images.amazon.com/images/P/0385424728.0...
139,Interview with the Vampire,508,Anne Rice,1993,Ballantine Books,http://images.amazon.com/images/P/0345337662.0...
141,The Horse Whisperer,507,Nicholas Evans,1996,Dell,http://images.amazon.com/images/P/0440222656.0...
145,The Rainmaker,501,JOHN GRISHAM,1996,Dell,http://images.amazon.com/images/P/044022165X.0...
152,Message in a Bottle,496,Nicholas Sparks,1998,Warner Books,http://images.amazon.com/images/P/0446523569.0...
157,The Poisonwood Bible: A Novel,494,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...
158,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,MITCH ALBOM,1997,Doubleday,http://images.amazon.com/images/P/0385484518.0...
161,Good in Bed,490,Jennifer Weiner,2002,Washington Square Press,http://images.amazon.com/images/P/0743418174.0...
163,Jurassic Park,488,Michael Crichton,1999,Ballantine Books,http://images.amazon.com/images/P/0345370775.0...
170,The Client,483,John Grisham,1993,Doubleday Books,http://images.amazon.com/images/P/038542471X.0...
174,Dreamcatcher,481,Stephen King,2001,Scribner,http://images.amazon.com/images/P/0743211383.0...
186,The Partner,478,John Grisham,1997,Doubleday Books,http://images.amazon.com/images/P/0385472951.0...
190,She's Come Undone (Oprah's Book Club),468,Wally Lamb,1998,Pocket,http://images.amazon.com/images/P/0671021001.0...
191,Hannibal,468,Thomas Harris,2000,Dell Publishing Company,http://images.amazon.com/images/P/0440224675.0...
203,The Reader,466,Bernhard Schlink,1997,Random House,http://images.amazon.com/images/P/0679442790.0...
208,The King of Torts,458,John Grisham,2003,Doubleday Books,http://images.amazon.com/images/P/0385508042.0...
212,Suzanne's Diary for Nicholas,457,James Patterson,2001,"Little, Brown",http://images.amazon.com/images/P/0316969443.0...

### Collaborative-based Recommendation System

**Approach:**

Our collaborative-based recommendation system aims to leverage user ratings on various books to provide personalized recommendations. The system utilizes two primary datasets: rating data and book data.

**Datasets:**

1. **Rating Data:**
   - Contains user ratings for different books.
   - Columns: `User-ID`, `ISBN`, `Book-Rating`

2. **User Data:**
   - Includes information about users such as location and age.
   - Columns: `User-ID`, `Location`, `Age`

3. **Book Data:**
   - Provides details about books including title, author, publication year, and publisher.
   - Columns: `ISBN`, `Book-Title`, `Book-Author`, `Year-Of-Publication`, `Publisher`, `Image-URL-S`, `Image-URL-M`, `Image-URL-L`

**Methodology:**

1. **Data Integration:**
   - We merge the rating data with user data and book data using common identifiers (`User-ID` and `ISBN`). This consolidation facilitates a comprehensive analysis.

2. **User-Item Matrix Construction:**
   - A pivotal step involves constructing a user-item matrix where rows correspond to users, columns represent books, and each cell captures the rating provided by a user for a specific book.
   - As not all users would have rated all books, the matrix tends to be sparse.

3. **Similarity Calculation:**
   - Utilizing measures like cosine similarity or Pearson correlation coefficient, we compute similarities between users or items.
   - By analyzing ratings given by users to different books, we establish similarity between users based on their preferences and tendencies.

4. **Recommendation Generation:**
   - Given a target user, we identify similar users based on calculated similarity scores.
   - Recommendations are then generated by suggesting books highly rated by similar users but not yet rated by the target user.
   - Techniques such as neighborhood-based collaborative filtering or matrix factorization can be employed for recommendation generation.

**Evaluation:**

   - To assess the effectiveness of our recommendation system, we employ metrics such as precision, recall, or mean average precision.
   - The dataset is typically split into training and testing sets to evaluate the system's performance accurately.

In [44]:
new_data = rating.merge(book, on='ISBN')

In [50]:
users_rating = new_data.groupby('User-ID').count()['Book-Rating'] > 200

In [46]:
users_high_rating = users_rating[users_rating].index
users_high_rating

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=811)

In [54]:
filter_rating = new_data[new_data['User-ID'].isin(users_high_rating)]
filter_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [61]:
top_50_users_rated_book = filter_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books = top_50_users_rated_book[top_50_users_rated_book].index

In [62]:
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [63]:
final_rating = filter_rating[filter_rating['Book-Title'].isin(famous_books)]
final_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [64]:
final_rating.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [66]:
pt =final_rating.pivot_table(index='Book-Title', columns='User-ID', values='Book-Rating')
pt.fillna(0, inplace=True)

In [67]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

### 📊 Data Preparation:
Our dataset is primed and ready. Each book is represented by a vector containing 810 numbers.

### 📐 Approach:
We're set to compute the Euclidean distance for each book to power our recommendation system.

### 🔍 Euclidean Distance:
This metric will measure the straight-line distance between two points in our 810-dimensional space.

### 📚 Recommendation System:
By leveraging the Euclidean distance, we'll identify similar books for our recommendations.

### 🚀 Next Steps:
1. Calculate the Euclidean distance between all pairs of books.
2. Utilize the distances to select books with the smallest values for recommendations.

### 💡 Note:
We'll need to handle aspects like normalization and missing values to ensure the accuracy of our recommendations.

### 🌟 Benefits:
- Tailored recommendations for users
- Improved user engagement and satisfaction

### 🛠️ Implementation:
Keep an eye out as we embark on building a robust recommendation system using the Euclidean distance metric!

In [69]:
from sklearn.metrics.pairwise import cosine_similarity

In [70]:
similarity_score = cosine_similarity(pt)

In [71]:
similarity_score.shape

(706, 706)

In [74]:
similarity_score[0]

array([1.        , 0.10255025, 0.01220856, 0.        , 0.05367224,
       0.02774901, 0.08216491, 0.13732869, 0.03261686, 0.03667591,
       0.02322418, 0.06766487, 0.02083978, 0.09673735, 0.13388865,
       0.08303112, 0.11153543, 0.05100411, 0.02517784, 0.11706383,
       0.        , 0.14333793, 0.07847534, 0.06150451, 0.08723968,
       0.        , 0.07009814, 0.13658681, 0.07600328, 0.12167134,
       0.00768046, 0.01473221, 0.        , 0.07965814, 0.04522617,
       0.01556271, 0.09495938, 0.0182307 , 0.02610465, 0.07984012,
       0.11679969, 0.0569124 , 0.08354155, 0.08471898, 0.08785938,
       0.05491435, 0.0548505 , 0.27026514, 0.09779123, 0.06016046,
       0.08958835, 0.06748675, 0.        , 0.04468098, 0.01920872,
       0.        , 0.05629067, 0.00557964, 0.07877059, 0.05219479,
       0.18908177, 0.        , 0.01240656, 0.02984572, 0.04279502,
       0.12680125, 0.16566735, 0.        , 0.13357242, 0.06615478,
       0.        , 0.        , 0.        , 0.10968075, 0.02806606,
       0.04521795, 0.02613277, 0.06876131, 0.01331627, 0.10519138,
       0.03349457, 0.01363458, 0.23669374, 0.        , 0.10397941,
       0.06167753, 0.14176273, 0.11661083, 0.08331012, 0.00850895,
       0.06715433, 0.        , 0.15850821, 0.0328052 , 0.01068915,
       0.02579782, 0.02114859, 0.02687779, 0.02175821, 0.        ,
       0.01601663, 0.12114266, 0.04768603, 0.05819184, 0.06510722,
       0.        , 0.0476705 , 0.05273165, 0.0281001 , 0.06524573,
       0.02116345, 0.02097868, 0.07422249, 0.01752778, 0.03734567,
       0.        , 0.01579666, 0.11039448, 0.16527277, 0.15514319,
       0.06237454, 0.08139489, 0.05655414, 0.07458203, 0.03771888,
       0.0593633 , 0.02955369, 0.03355603, 0.04734093, 0.01006643,
       0.01671982, 0.07258935, 0.        , 0.        , 0.        ,
       0.02428501, 0.03067819, 0.0997498 , 0.        , 0.01690152,
       0.02410862, 0.0281084 , 0.        , 0.        , 0.01812877,
       0.02880827, 0.        , 0.05995157, 0.02127671, 0.1034119 ,
       0.02766748, 0.10684795, 0.09898722, 0.14145186, 0.05007429,
       0.09428289, 0.01411249, 0.        , 0.07835976, 0.00882242,
       0.04515898, 0.        , 0.01281412, 0.04003334, 0.07477661,
       0.01217906, 0.01887393, 0.02667484, 0.01432864, 0.14702847,
       0.06087282, 0.02578321, 0.02741876, 0.        , 0.14909595,
       0.05606788, 0.        , 0.03199916, 0.03643817, 0.        ,
       0.01962921, 0.22222254, 0.01515845, 0.09673268, 0.02190023,
       0.02013549, 0.05400331, 0.07262017, 0.01111637, 0.03649872,
       0.05994664, 0.        , 0.14691167, 0.02086005, 0.10359635,
       0.09794375, 0.06609997, 0.12871083, 0.08992739, 0.01147457,
       0.02460165, 0.        , 0.18049207, 0.05141892, 0.0477174 ,
       0.10849696, 0.13278139, 0.05915288, 0.05372984, 0.034785  ,
       0.        , 0.09203039, 0.06388401, 0.04773328, 0.15570975,
       0.08420691, 0.12338217, 0.0878469 , 0.08205945, 0.12177532,
       0.02433703, 0.00272862, 0.        , 0.        , 0.03671505,
       0.15280984, 0.0370943 , 0.07458136, 0.09746697, 0.05416091,
       0.10266993, 0.07574414, 0.06426526, 0.0360174 , 0.01559752,
       0.02033559, 0.02463593, 0.        , 0.03349154, 0.02135369,
       0.0190337 , 0.06806265, 0.02032116, 0.11784706, 0.07839488,
       0.08422558, 0.        , 0.02040796, 0.        , 0.04698246,
       0.08294513, 0.13974514, 0.01234525, 0.13510608, 0.07423489,
       0.11841889, 0.04930091, 0.01621668, 0.02633023, 0.04815972,
       0.01959826, 0.10174253, 0.13257638, 0.        , 0.0551027 ,
       0.0186115 , 0.        , 0.04504598, 0.03482459, 0.16503292,
       0.08466191, 0.06795353, 0.02987653, 0.        , 0.        ,
       0.08781993, 0.07885279, 0.04799058, 0.01467964, 0.02123837,
       0.04549923, 0.08673969, 0.00885998, 0.02880637, 0.02022145,
       0.02414122, 0.12548312, 0.        , 0.02482518, 0.06520606,
       0.        , 0.0606983 , 0.01177824, 0.13974105, 0.01978844,
       0.01260824, 0.08608601, 0.04433883, 0.02943085, 0.02242496,
       0.06541868, 0.07866868, 0.14281399, 0.11979305, 0.01858409,
       0.13445377, 0.04809338, 0.09790644, 0.        , 0.17415731,
       0.07437756, 0.        , 0.12389065, 0.01042391, 0.02580849,
       0.        , 0.0895139 , 0.04005551, 0.19182231, 0.02267512,
       0.01730347, 0.03054044, 0.07008822, 0.10084626, 0.10467615,
       0.01683462, 0.12468283, 0.10266459, 0.03549836, 0.02667484,
       0.07652765, 0.08474056, 0.01831977, 0.02177482, 0.15293362,
       0.        , 0.        , 0.01063251, 0.02153089, 0.02946443,
       0.        , 0.02076783, 0.01194825, 0.00953675, 0.2067554 ,
       0.01554292, 0.0390266 , 0.06681046, 0.09014973, 0.05914735,
       0.06206857, 0.        , 0.02005959, 0.07843566, 0.16337845,
       0.07161075, 0.        , 0.14595258, 0.07561631, 0.02939738,
       0.04779629, 0.01807238, 0.11362722, 0.09791273, 0.07999693,
       0.08912337, 0.10941777, 0.        , 0.02115842, 0.0600393 ,
       0.01797154, 0.05755408, 0.02166863, 0.09754449, 0.13107652,
       0.        , 0.06829904, 0.09132922, 0.        , 0.02781406,
       0.01533368, 0.06113179, 0.01757286, 0.02471294, 0.0180158 ,
       0.11789806, 0.06468143, 0.13904191, 0.        , 0.06671644,
       0.        , 0.        , 0.05762086, 0.02266096, 0.00844876,
       0.02297481, 0.07136276, 0.15305514, 0.06039874, 0.        ,
       0.08996912, 0.01545947, 0.10135299, 0.        , 0.01676344,
       0.        , 0.0502188 , 0.16041182, 0.        , 0.13439733,
       0.12508514, 0.02329035, 0.0198727 , 0.01105674, 0.02548034,
       0.00896044, 0.08246122, 0.01902896, 0.07025003, 0.0216367 ,
       0.12822982, 0.09998772, 0.08642895, 0.06355197, 0.02883024,
       0.04335826, 0.0470659 , 0.05223733, 0.        , 0.08982751,
       0.00875634, 0.09923542, 0.10228551, 0.        , 0.12307492,
       0.01758929, 0.02028125, 0.1033827 , 0.13028171, 0.08988894,
       0.09005001, 0.05332049, 0.08033436, 0.04597795, 0.06139888,
       0.02300709, 0.02304904, 0.06523041, 0.01915363, 0.        ,
       0.04542766, 0.        , 0.        , 0.05261954, 0.01317088,
       0.        , 0.        , 0.0485931 , 0.0734819 , 0.10354481,
       0.01718807, 0.09919937, 0.08091989, 0.00358835, 0.04757132,
       0.11122765, 0.05143481, 0.0566614 , 0.        , 0.06087719,
       0.10800615, 0.        , 0.07554686, 0.        , 0.13644384,
       0.04796763, 0.16104067, 0.        , 0.01759864, 0.05438295,
       0.        , 0.08100801, 0.13090711, 0.00581844, 0.07150547,
       0.05428487, 0.06143184, 0.05161653, 0.1951182 , 0.1149488 ,
       0.06513047, 0.06401961, 0.        , 0.        , 0.10853662,
       0.11400426, 0.0463925 , 0.01825277, 0.        , 0.01195201,
       0.21057744, 0.05809707, 0.04349156, 0.02646256, 0.07276403,
       0.05264857, 0.07242165, 0.06790898, 0.01626564, 0.02431809,
       0.02093565, 0.13617057, 0.11784149, 0.08588206, 0.09284352,
       0.11277297, 0.06868983, 0.08200947, 0.13369059, 0.        ,
       0.19972625, 0.02286207, 0.0806288 , 0.        , 0.05756015,
       0.06738056, 0.        , 0.19656288, 0.06306426, 0.03499381,
       0.06123119, 0.09596456, 0.02180168, 0.02317515, 0.06476149,
       0.07052241, 0.08280452, 0.1700872 , 0.07213921, 0.01172201,
       0.08541218, 0.17990898, 0.08007284, 0.01739625, 0.16728777,
       0.26396194, 0.1840891 , 0.05600273, 0.04133586, 0.06911015,
       0.14456847, 0.22626397, 0.19208896, 0.0239334 , 0.20025064,
       0.01507653, 0.05144282, 0.1233368 , 0.1420166 , 0.02472079,
       0.08563805, 0.02363426, 0.12794024, 0.01083153, 0.07352436,
       0.09532519, 0.03421895, 0.07194212, 0.02297079, 0.15344079,
       0.08856302, 0.        , 0.        , 0.01878656, 0.09772942,
       0.04404359, 0.15211972, 0.0152225 , 0.10307399, 0.05715789,
       0.04600056, 0.06303899, 0.06572303, 0.14421331, 0.08272478,
       0.        , 0.04203701, 0.02276077, 0.17381829, 0.01909967,
       0.16000268, 0.14681486, 0.        , 0.05940546, 0.07725115,
       0.07464763, 0.06546696, 0.07021577, 0.18921368, 0.02494136,
       0.01705027, 0.05437622, 0.04932819, 0.        , 0.11445399,
       0.08001595, 0.12858515, 0.02306658, 0.06129105, 0.02090769,
       0.04550867, 0.1026659 , 0.10725982, 0.0260534 , 0.00173709,
       0.0987294 , 0.08077482, 0.02159226, 0.01614275, 0.0208464 ,
       0.09797466, 0.01906731, 0.18571699, 0.05344577, 0.18925314,
       0.05894189, 0.01488161, 0.1202478 , 0.09840359, 0.01048126,
       0.10596224, 0.07617195, 0.0805439 , 0.        , 0.23299389,
       0.01073642, 0.13573542, 0.04578552, 0.14440017, 0.        ,
       0.12522954, 0.0645501 , 0.02817522, 0.14445559, 0.01721045,
       0.09508161, 0.0517902 , 0.18410818, 0.08704224, 0.10990764,
       0.10850377, 0.03954865, 0.0383631 , 0.02463491, 0.07845405,
       0.03455548, 0.03007681, 0.02484076, 0.04223674, 0.14444517,
       0.12340234, 0.01510201, 0.0284437 , 0.02132016, 0.07391778,
       0.08904276, 0.15893871, 0.06947574, 0.01060787, 0.        ,
       0.09993169, 0.05711356, 0.09488374, 0.00948943, 0.13365876,
       0.05794064, 0.        , 0.06721284, 0.02066998, 0.        ,
       0.01839428, 0.        , 0.12655364, 0.08418288, 0.09095705,
       0.00730589, 0.08143881, 0.        , 0.04218803, 0.08392849,
       0.07785801, 0.        , 0.07151794, 0.02407593, 0.01635126,
       0.03734567, 0.05237227, 0.01140169, 0.00968725, 0.12530648,
       0.00909905, 0.05864096, 0.01769644, 0.12110367, 0.07347567,
       0.04316046])

### 📊 Similarity Score Analysis:

Here's a snippet of the similarity score array, which measures the similarity between each book and all other books in the dataset. Let's break it down:

- Each element in the array corresponds to the similarity score between the book at index 0 and every other book in the dataset.
- A similarity score of 1.0 indicates a perfect match (the book compared with itself).
- Lower similarity scores signify less similarity between books, while higher scores indicate greater similarity.
- The similarity scores provide valuable insights into which books are most closely related to each other in terms of user ratings.

By analyzing these similarity scores, we can identify books with similar characteristics and recommend them to users based on their preferences. This enables us to create a robust recommendation system tailored to the interests of our audience. 📚🔍

# Let's Create a Recommendation Function

In [78]:
import numpy as np
np.where(pt.index=='Year of Wonders')[0][0]

701

In [79]:
index = np.where(pt.index=='Year of Wonders')[0][0]

In [82]:
list(enumerate(similarity_score[index]))

[(0, 0.05864096359154978),
 (1, 0.052352930346605486),
 (2, 0.06854925775063087),
 (3, 0.10863774228275982),
 (4, 0.0),
 (5, 0.06491944055564465),
 (6, 0.0),
 (7, 0.1314341847437074),
 (8, 0.126244664870183),
 (9, 0.0723972186805046),
 (10, 0.0),
 (11, 0.2399287128242759),
 (12, 0.05484953161349921),
 (13, 0.05490771499970819),
 (14, 0.03497253669839795),
 (15, 0.057509161260159564),
 (16, 0.0),
 (17, 0.1595559269694617),
 (18, 0.0),
 (19, 0.09342887058681101),
 (20, 0.0),
 (21, 0.09584860210026594),
 (22, 0.04198052559510889),
 (23, 0.0),
 (24, 0.0),
 (25, 0.11454786534881817),
 (26, 0.06068937760393794),
 (27, 0.05071831293409738),
 (28, 0.06912568857161656),
 (29, 0.08366066459469348),
 (30, 0.1091592873204125),
 (31, 0.08724293036839384),
 (32, 0.0),
 (33, 0.04748948242651238),
 (34, 0.05668266037102219),
 (35, 0.0),
 (36, 0.0),
 (37, 0.041984701695898456),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.07257331669301882),
 (42, 0.03186641503949967),
 (43, 0.07167124544432409),
 (44, 0.10357381472928827),
 (45, 0.05331117979161523),
 (46, 0.10714550719312019),
 (47, 0.04470635646169596),
 (48, 0.0),
 (49, 0.0),
 (50, 0.08714096689634797),
 (51, 0.0),
 (52, 0.0),
 (53, 0.04899945278295159),
 (54, 0.09668955917765668),
 (55, 0.0831559499238912),
 (56, 0.03779462923566409),
 (57, 0.13079185554547085),
 (58, 0.05923464421290583),
 (59, 0.14205798277033374),
 (60, 0.09620312785504243),
 (61, 0.0),
 (62, 0.0),
 (63, 0.0),
 (64, 0.13610050545969715),
 (65, 0.049239762630532015),
 (66, 0.07213736490902663),
 (67, 0.04684519753780023),
 (68, 0.12316475350531919),
 (69, 0.04515480372064131),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (73, 0.11426744742415978),
 (74, 0.036448435504985006),
 (75, 0.04228056858693573),
 (76, 0.0),
 (77, 0.12208779947038585),
 (78, 0.13532395360154234),
 (79, 0.0),
 (80, 0.0),
 (81, 0.0),
 (82, 0.048732917835563785),
 (83, 0.03214801269461212),
 (84, 0.0),
 (85, 0.0),
 (86, 0.0),
 (87, 0.09922272161077147),
 (88, 0.21161084671743188),
 (89, 0.0),
 (90, 0.0),
 (91, 0.0),
 (92, 0.1621799342993878),
 (93, 0.08993965948725001),
 (94, 0.08862039313078263),
 (95, 0.0),
 (96, 0.0),
 (97, 0.0),
 (98, 0.0),
 (99, 0.0),
 (100, 0.05269396707413136),
 (101, 0.1296109661997126),
 (102, 0.0),
 (103, 0.0655645381888423),
 (104, 0.022490969924074598),
 (105, 0.06620298037947446),
 (106, 0.053771561220387634),
 (107, 0.0),
 (108, 0.0),
 (109, 0.1091105681749892),
 (110, 0.0),
 (111, 0.06211699365166946),
 (112, 0.13630630317417974),
 (113, 0.1166879986198309),
 (114, 0.110578963091918),
 (115, 0.0),
 (116, 0.01818960004979694),
 (117, 0.04769885528623087),
 (118, 0.08166054401216308),
 (119, 0.11193286814711051),
 (120, 0.0),
 (121, 0.05936129529659103),
 (122, 0.046515122053151246),
 (123, 0.0),
 (124, 0.0),
 (125, 0.0873117055254175),
 (126, 0.0),
 (127, 0.06571295527509871),
 (128, 0.0),
 (129, 0.0),
 (130, 0.0),
 (131, 0.11498527993473567),
 (132, 0.04557532574140063),
 (133, 0.06984219781030947),
 (134, 0.0),
 (135, 0.11096744305125622),
 (136, 0.0),
 (137, 0.0),
 (138, 0.0),
 (139, 0.0),
 (140, 0.0),
 (141, 0.0),
 (142, 0.0),
 (143, 0.0),
 (144, 0.0),
 (145, 0.0644747469754267),
 (146, 0.0),
 (147, 0.0),
 (148, 0.0),
 (149, 0.0),
 (150, 0.05731185396871948),
 (151, 0.0),
 (152, 0.062361069223152224),
 (153, 0.034781020245253154),
 (154, 0.0),
 (155, 0.0),
 (156, 0.10678769850986794),
 (157, 0.07510581433326562),
 (158, 0.07960024582203154),
 (159, 0.0),
 (160, 0.20892789410178136),
 (161, 0.08933398037333104),
 (162, 0.0),
 (163, 0.0),
 (164, 0.0),
 (165, 0.0),
 (166, 0.11099366708524114),
 (167, 0.15006785534166456),
 (168, 0.10370922974261501),
 (169, 0.16317915930589139),
 (170, 0.04811260944175149),
 (171, 0.0),
 (172, 0.09495414184336962),
 (173, 0.07565830660026612),
 (174, 0.06688892086860072),
 (175, 0.0),
 (176, 0.0),
 (177, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.0),
 (181, 0.0),
 (182, 0.05699496389368122),
 (183, 0.08150202787651119),
 (184, 0.06484567379165507),
 (185, 0.05888428836441312),
 (186, 0.0),
 (187, 0.0),
 (188, 0.0),
 (189, 0.0),
 (190, 0.04601838548202029),
 (191, 0.0733726647573438),
 (192, 0.09372099451958509),
 (193, 0.0),
 (194, 0.0),
 (195, 0.0),
 (196, 0.0),
 (197, 0.04584750518100966),
 (198, 0.1544547177745964),
 (199, 0.0),
 (200, 0.0),
 (201, 0.0),
 (202, 0.0),
 (203, 0.0398037318314647),
 (204, 0.0),
 (205, 0.07477000783918114),
 (206, 0.08658181329461144),
 (207, 0.0),
 (208, 0.0),
 (209, 0.0),
 (210, 0.0),
 (211, 0.0),
 (212, 0.07689345205354388),
 (213, 0.0),
 (214, 0.08662736215892644),
 (215, 0.06650797639471259),
 (216, 0.13049627906039962),
 (217, 0.14138165877148162),
 (218, 0.047738909475951205),
 (219, 0.0),
 (220, 0.0),
 (221, 0.0),
 (222, 0.0),
 (223, 0.0),
 (224, 0.02516475215835776),
 (225, 0.030460899041299734),
 (226, 0.0),
 (227, 0.09643477565170828),
 (228, 0.029958022939122243),
 (229, 0.1335405031306427),
 (230, 0.02817726468609262),
 (231, 0.0319822094150743),
 (232, 0.034660608398538024),
 (233, 0.11849555633702616),
 (234, 0.0),
 (235, 0.0),
 (236, 0.0),
 (237, 0.0),
 (238, 0.0),
 (239, 0.0),
 (240, 0.0),
 (241, 0.12918631599416824),
 (242, 0.1356215142891467),
 (243, 0.03264937630916205),
 (244, 0.10270971930590606),
 (245, 0.0),
 (246, 0.0),
 (247, 0.0),
 (248, 0.13459242771327712),
 (249, 0.03170668741945781),
 (250, 0.0),
 (251, 0.16461011665402175),
 (252, 0.0),
 (253, 0.05186423628719008),
 (254, 0.0),
 (255, 0.08610562290550176),
 (256, 0.0),
 (257, 0.05928014516255176),
 (258, 0.0),
 (259, 0.06979878096097605),
 (260, 0.0),
 (261, 0.0),
 (262, 0.07001125871567501),
 (263, 0.04461444054874269),
 (264, 0.0),
 (265, 0.03857550664862228),
 (266, 0.0),
 (267, 0.052552899480486616),
 (268, 0.0),
 (269, 0.0),
 (270, 0.0605508172003274),
 (271, 0.19524585149904375),
 (272, 0.0),
 (273, 0.0),
 (274, 0.0581122212452699),
 (275, 0.0),
 (276, 0.0),
 (277, 0.0),
 (278, 0.0),
 (279, 0.0),
 (280, 0.0),
 (281, 0.036941040319458184),
 (282, 0.11076596098032547),
 (283, 0.0),
 (284, 0.0),
 (285, 0.0),
 (286, 0.10967286994649336),
 (287, 0.0),
 (288, 0.0),
 (289, 0.0),
 (290, 0.0),
 (291, 0.0),
 (292, 0.0),
 (293, 0.04585950655921517),
 (294, 0.0),
 (295, 0.0),
 (296, 0.0),
 (297, 0.0),
 (298, 0.0),
 (299, 0.0),
 (300, 0.06978931870707177),
 (301, 0.0),
 (302, 0.1698361848862926),
 (303, 0.0),
 (304, 0.0),
 (305, 0.0636469997546263),
 (306, 0.06027618734122724),
 (307, 0.038346149208098014),
 (308, 0.0),
 (309, 0.060661778407162366),
 (310, 0.0),
 (311, 0.0),
 (312, 0.10770631649625007),
 (313, 0.0),
 (314, 0.0),
 (315, 0.0),
 (316, 0.0),
 (317, 0.0),
 (318, 0.08056423087102248),
 (319, 0.0),
 (320, 0.05123484648549246),
 (321, 0.0),
 (322, 0.06010086929639953),
 (323, 0.039363671120401046),
 (324, 0.0),
 (325, 0.07384683061831572),
 (326, 0.10485269065834715),
 (327, 0.12304617265701004),
 (328, 0.20386666560840577),
 (329, 0.0),
 (330, 0.0),
 (331, 0.0),
 (332, 0.02712203981381857),
 (333, 0.0),
 (334, 0.06988118110211111),
 (335, 0.0),
 (336, 0.07335856894614576),
 (337, 0.0),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (342, 0.0),
 (343, 0.0),
 (344, 0.0),
 (345, 0.0),
 (346, 0.0),
 (347, 0.0),
 (348, 0.12689853197994594),
 (349, 0.0),
 (350, 0.05234310262616758),
 (351, 0.05930115212481986),
 (352, 0.0),
 (353, 0.0),
 (354, 0.06727253051476255),
 (355, 0.08124001921931469),
 (356, 0.0),
 (357, 0.1600590694298263),
 (358, 0.10809356058952492),
 (359, 0.0),
 (360, 0.0),
 (361, 0.0),
 (362, 0.052162085199138945),
 (363, 0.05103023169946677),
 (364, 0.05160513131891811),
 (365, 0.11104848385087052),
 (366, 0.13599221005206816),
 (367, 0.12494165414792688),
 (368, 0.03480511595459176),
 (369, 0.0),
 (370, 0.0),
 (371, 0.0),
 (372, 0.0),
 (373, 0.10697228468988353),
 (374, 0.09512551268121881),
 (375, 0.06987070141381282),
 (376, 0.05617516640894927),
 (377, 0.0),
 (378, 0.10520255774773063),
 (379, 0.0658850211570258),
 (380, 0.051077689332079936),
 (381, 0.0767238362999906),
 (382, 0.0),
 (383, 0.0),
 (384, 0.08001605116385566),
 (385, 0.08800619218383045),
 (386, 0.062066347908514875),
 (387, 0.07401964547793718),
 (388, 0.0),
 (389, 0.05453266790857223),
 (390, 0.07534523417653405),
 (391, 0.0),
 (392, 0.07363461417767872),
 (393, 0.0),
 (394, 0.03891445695736206),
 (395, 0.0),
 (396, 0.0),
 (397, 0.03933299760666667),
 (398, 0.0),
 (399, 0.0),
 (400, 0.029923595997883783),
 (401, 0.0),
 (402, 0.05052221819788774),
 (403, 0.0),
 (404, 0.07878706559958931),
 (405, 0.15013702463246303),
 (406, 0.0),
 (407, 0.050884739346690744),
 (408, 0.0),
 (409, 0.0),
 (410, 0.030193358060273654),
 (411, 0.0),
 (412, 0.0),
 (413, 0.07275228938573904),
 (414, 0.03260021726786588),
 (415, 0.0),
 (416, 0.0),
 (417, 0.0),
 (418, 0.0),
 (419, 0.0),
 (420, 0.04577252965221421),
 (421, 0.04980439460163408),
 (422, 0.0),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0663619837723019),
 (427, 0.0),
 (428, 0.0),
 (429, 0.0),
 (430, 0.0),
 (431, 0.11667642782377459),
 (432, 0.06256803675776074),
 (433, 0.0),
 (434, 0.03105849682583473),
 (435, 0.0),
 (436, 0.0),
 (437, 0.018739628820000766),
 (438, 0.06857932264576108),
 (439, 0.0),
 (440, 0.03095257468970046),
 (441, 0.02132921953690357),
 (442, 0.15857777925834807),
 (443, 0.0),
 (444, 0.05454837401201965),
 (445, 0.05839117550944693),
 (446, 0.0),
 (447, 0.04433988182103057),
 (448, 0.0),
 (449, 0.0),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (453, 0.051934752270793125),
 (454, 0.0),
 (455, 0.0),
 (456, 0.0),
 (457, 0.140817295835105),
 (458, 0.0),
 (459, 0.06905221793512681),
 (460, 0.0),
 (461, 0.0),
 (462, 0.0713863255930226),
 (463, 0.08246995969088695),
 (464, 0.0),
 (465, 0.05692303378916778),
 (466, 0.03461279792595147),
 (467, 0.07669579178774664),
 (468, 0.0),
 (469, 0.0686685050779708),
 (470, 0.0658028189775958),
 (471, 0.0),
 (472, 0.0),
 (473, 0.0),
 (474, 0.040867507457067215),
 (475, 0.12835316074310005),
 (476, 0.09370114180773388),
 (477, 0.06170494627684369),
 (478, 0.05955296282067819),
 (479, 0.03727445637232564),
 (480, 0.0),
 (481, 0.0),
 (482, 0.0),
 (483, 0.040199026662086086),
 (484, 0.09318331660201949),
 (485, 0.0),
 (486, 0.0),
 (487, 0.0),
 (488, 0.06219389110351961),
 (489, 0.06263787938805293),
 (490, 0.13686029243500278),
 (491, 0.0),
 (492, 0.14143090314549087),
 (493, 0.1265981270594462),
 (494, 0.12563941242006338),
 (495, 0.10638707687194957),
 (496, 0.036722806207189485),
 (497, 0.0),
 (498, 0.0),
 (499, 0.0),
 (500, 0.16799636994311395),
 (501, 0.07050122634033068),
 (502, 0.06430796369680342),
 (503, 0.10209831994161357),
 (504, 0.042245345256798024),
 (505, 0.0),
 (506, 0.05718332769587819),
 (507, 0.07620804428558421),
 (508, 0.0),
 (509, 0.09000607561516297),
 (510, 0.08265276539111562),
 (511, 0.06165066887678071),
 (512, 0.041015383789581),
 (513, 0.06196228109847886),
 (514, 0.0),
 (515, 0.06466541641614906),
 (516, 0.06321296741590232),
 (517, 0.05033719306041964),
 (518, 0.058000331063791336),
 (519, 0.08505719656856141),
 (520, 0.06461062646645101),
 (521, 0.0),
 (522, 0.29179150338901577),
 (523, 0.0),
 (524, 0.12153610634003009),
 (525, 0.0),
 (526, 0.0),
 (527, 0.0),
 (528, 0.05061470739297261),
 (529, 0.0921024164129468),
 (530, 0.08505572400990945),
 (531, 0.08147585855598524),
 (532, 0.043932497182401),
 (533, 0.0),
 (534, 0.0),
 (535, 0.05459186749312044),
 (536, 0.12993769133567581),
 (537, 0.0652358918175953),
 (538, 0.07582576649027555),
 (539, 0.15117432136592854),
 (540, 0.0),
 (541, 0.053203792015945266),
 (542, 0.0),
 (543, 0.0),
 (544, 0.10450044100730557),
 (545, 0.04666429371804205),
 (546, 0.056602298851270265),
 (547, 0.04913236766382441),
 (548, 0.03472162955228409),
 (549, 0.051440991098040456),
 (550, 0.09980701584550807),
 (551, 0.09066966631063293),
 (552, 0.07688123580162275),
 (553, 0.0),
 (554, 0.14836590976240843),
 (555, 0.0),
 (556, 0.03330514016351389),
 (557, 0.11541154870164738),
 (558, 0.03897626768264488),
 (559, 0.0),
 (560, 0.12021129268772646),
 (561, 0.06586358467649839),
 (562, 0.04498354456934583),
 (563, 0.0570163573053244),
 (564, 0.1522395398312379),
 (565, 0.03801399405750002),
 (566, 0.0),
 (567, 0.0),
 (568, 0.0),
 (569, 0.07534523417653405),
 (570, 0.1505001075030177),
 (571, 0.20285158137792297),
 (572, 0.0),
 (573, 0.09508755131111836),
 (574, 0.04688909689459398),
 (575, 0.0),
 (576, 0.1232460055980335),
 (577, 0.0),
 (578, 0.0),
 (579, 0.07679632144046994),
 (580, 0.039236221943415),
 (581, 0.04722864328053877),
 (582, 0.0),
 (583, 0.05460480496706996),
 (584, 0.0),
 (585, 0.126020265688215),
 (586, 0.19546373719625004),
 (587, 0.0),
 (588, 0.06825844824050882),
 (589, 0.12436496676755394),
 (590, 0.09112970115054511),
 (591, 0.0),
 (592, 0.0),
 (593, 0.0),
 (594, 0.0),
 (595, 0.0),
 (596, 0.07023366853891225),
 (597, 0.07800223284587328),
 (598, 0.08962560567508489),
 (599, 0.0),
 (600, 0.0),
 (601, 0.0),
 (602, 0.0),
 (603, 0.08627291127317793),
 (604, 0.0),
 (605, 0.07767996464687794),
 (606, 0.044413561026695),
 (607, 0.0),
 (608, 0.0672149069619457),
 (609, 0.07075060943590715),
 (610, 0.0),
 (611, 0.07373231828297103),
 (612, 0.0858356313474635),
 (613, 0.0),
 (614, 0.0),
 (615, 0.17406362259136657),
 (616, 0.09485970681258482),
 (617, 0.05262038923920928),
 (618, 0.0),
 (619, 0.0),
 (620, 0.04415507976627496),
 (621, 0.0),
 (622, 0.19731498002073453),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (626, 0.0),
 (627, 0.1884963795157346),
 (628, 0.04257013391721309),
 (629, 0.03678170031149888),
 (630, 0.0),
 (631, 0.022554195180880088),
 (632, 0.04571637954451799),
 (633, 0.07099200895029141),
 (634, 0.049742964441501294),
 (635, 0.0),
 (636, 0.06777519651234921),
 (637, 0.0),
 (638, 0.0),
 (639, 0.1399839551962358),
 (640, 0.020027747433290843),
 (641, 0.0),
 (642, 0.0),
 (643, 0.0),
 (644, 0.06661363741353449),
 (645, 0.03680165754309281),
 (646, 0.0),
 (647, 0.018911938449809602),
 (648, 0.062479617827616615),
 (649, 0.06428284970405358),
 (650, 0.05564076325464673),
 (651, 0.0),
 (652, 0.0),
 (653, 0.0648381636279546),
 (654, 0.0),
 (655, 0.0),
 (656, 0.0),
 (657, 0.041910236442453556),
 (658, 0.052108842468093414),
 (659, 0.021718336281817675),
 (660, 0.0),
 (661, 0.0),
 (662, 0.0),
 (663, 0.0),
 (664, 0.07565788241507705),
 (665, 0.11812360268910042),
 (666, 0.04198883698803612),
 (667, 0.0),
 (668, 0.08375853715317126),
 (669, 0.0),
 (670, 0.0),
 (671, 0.023866453069916325),
 (672, 0.0),
 (673, 0.08919940278791375),
 (674, 0.04416941853670301),
 (675, 0.17626007378569564),
 (676, 0.0),
 (677, 0.0),
 (678, 0.06120294163707534),
 (679, 0.06190456121534263),
 (680, 0.060516325134184576),
 (681, 0.0),
 (682, 0.016580533094078895),
 (683, 0.04247818535409855),
 (684, 0.0),
 (685, 0.06009008849297935),
 (686, 0.0),
 (687, 0.0),
 (688, 0.08076528781255901),
 (689, 0.13181076192707014),
 (690, 0.10802252901093148),
 (691, 0.07350632623496073),
 (692, 0.034214530882357895),
 (693, 0.042772696528832276),
 (694, 0.05020856820845829),
 (695, 0.0),
 (696, 0.18118388471184896),
 (697, 0.0),
 (698, 0.0),
 (699, 0.0),
 (700, 0.07184511844343185),
 (701, 1.0),
 (702, 0.0),
 (703, 0.0),
 (704, 0.08133023581481905),
 (705, 0.0)]

* Now, let's perform the sorting because we are receiving random values.

In [88]:
similar_items = sorted(enumerate(similarity_score[index]), key=lambda x: x[1], reverse=True)[1:7]

In [92]:
for i in similar_items:
    print(i[0])

522
11
88
160
328
571

* Here we are getting 6 books indexes now let's print the name of those indexes

In [93]:
for i in similar_items:
    print(pt.index[i[0]])

The Eight
A Heartbreaking Work of Staggering Genius
Bridget Jones: The Edge of Reason
Drowning Ruth (Oprah's Book Club)
Midwives: A Novel
The Mists of Avalon

## Now let's Convert in fuction

In [94]:
def recommender(book_name):
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(enumerate(similarity_score[index]), key=lambda x: x[1], reverse=True)[1:7]
    for i in similar_items:
        print(pt.index[i[0]])

In [95]:
recommender('The Rainmaker')

The Firm
The Chamber
The Partner
The Client
The Pelican Brief
The Runaway Jury

In [96]:
recommender('A Heartbreaking Work of Staggering Genius')

Year of Wonders
The Giver (21st Century Reference)
Blessings
The Girls' Guide to Hunting and Fishing
Plainsong (Vintage Contemporaries)
A Civil Action

In [97]:
recommender('A Walk to Remember')

The Rescue
Nights in Rodanthe
The Notebook
Granny Dan
A Bend in the Road
The Dogs of Babel (Today Show Book Club #12)